services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userdb
      SPRING_DATASOURCE_USERNAME: user1
      SPRING_DATASOURCE_PASSWORD: password

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5433"